/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PersonModule"
 * 	found in "person.asn1"
 * 	`asn1c -fnative-types`
 */

#ifndef	_Person_H_
#define	_Person_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Person */
typedef struct Person {
	long	 height;
	long	 width;
	OCTET_STRING_t	 name;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Person_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Person;

#ifdef __cplusplus
}
#endif

#endif	/* _Person_H_ */
#include <asn_internal.h>
